name: Build ORRI
on:
  schedule:
    - cron: "5 7 2 * *"   # monthly on the 2nd at 07:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas fredapi
      - name: Build ORRI
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python scripts/build_orri.py
      - name: Commit CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Update ORRI CSVs [skip ci]" || echo "No changes"
          git push
